### ISSUE TITLE
Lighting Issues on Ice

### ISSUE THREAD

**Issue by SkeleBones** [rre36/ShaderpackIssueTracker#43] opened 2022-02-01 18:51 UTC
**Describe the bug**
Lighting does not display correctly on ice. It seems to revert to normal Minecraft lighting instead of smooth shader lighting. 

**To Reproduce**
1. Use Nostalgia Shaders

**Expected behavior**
I expected the lighting to look the same as it does on other blocks instead of being reverted to what looks like default Minecraft lighting

**Screenshots**
![image](https://user-images.githubusercontent.com/38815328/152030758-25ef53f9-3588-41dc-9107-a8c8aaae506b.png)

**Environment (please complete the following information):**
Optifine Version: OptiFine HD U H4
Minecraft Version: 1.18.1
Shaderpack Version: Nostalgia v4.0
Graphics Card and Driver Version: NVIDIA GeForce RTX 360 and 511.23
Operating System: Windows 11
CPU: AMD Ryzen 5 4600G
Amount of System Memory (total and assigned to Java): 16 GB and 12 GB to Java

**Additional context**
I have tried disabling and enabled multiple settings with no change to them lighting on ice.

**Comment by rre36** [comment] 2022-02-01 18:53
This issue is caused by the vanilla lightmap, not the shaderpack unfortunately. So it can't be fixed on my end, it has been an issue for a long time.

**Closed as completed** 2022-04-08 18:13 UTC
Labels: Wontfix, Iris/Optifine Issue
