### ISSUE TITLE
Lightning and motion blur issues.

### ISSUE THREAD

**Issue by Fichuwa** [rre36/ShaderpackIssueTracker#41] opened 2021-11-12 23:59 UTC
Issue:
When I use the latest Kappa shaders with Minecraft 1.17.1 and OptiFine HD U H1/other version (Does not even work with Iris Shaders), I see bright circle around me when I look at the water. Normally it shouldn't be there. Also the motion blur is not working as expected, when moving the cursor slightly faster. There are even more issues underwater like noise. 

Minecraft and shader versions are latest and on default settings, changing the settings does not remove the issue.
My game and drivers are all up to date. (I am using Nvidia graphics card and Intel processor)

If there are any important details left out, I can add them later.

Light ring around me in water (Kappa with default settings):
![Screenshot 2021-11-13 011403](https://user-images.githubusercontent.com/91141402/141595672-0bc48a53-947d-48dd-b082-c1eabde0bb3c.png)
Motion blur issue (Kappa with default settings):
![Screenshot 2021-11-13 011725](https://user-images.githubusercontent.com/91141402/141595680-9c06ac5d-f87f-4d27-b714-9ab3c114aa73.png)
Noise in water (HardTop Vanillaaccurate 128x and Kappa with default settings):
![Screenshot 2021-11-13 022838](https://user-images.githubusercontent.com/91141402/141598229-026a7fb0-4652-4911-a131-e8ff27ad247e.png)
Something that should not be visible (HardTop Vanillaccurate 128x and Kappa with default settings):
![Screenshot 2021-11-13 022722](https://user-images.githubusercontent.com/91141402/141598231-4fc7debb-182d-481f-8160-3b264dc52d8b.png)

Aditionally: 
I would love to have border fog/distant fade, to remove visible chunk edges (Kappa Shaders). 
Is it possible to buy Kappa PT Shaders without monthly subscription to Pateron, because I am always against monthly subscriptions and prefer to buy things once, even if they cost more.

Thank you for your shaders!

**Comment by DeltaRicho** [comment] 2021-11-18 01:06
I have been doing a lot of playing around and I have similar issues caused by the setting Penumbra Scale, if I set it to 0.1 I see a lot of shadow issues, but if I set it to 3.0 it seems to resolve. I then try to turn off Variable Penumbra Shadows (the setting right below) and it doesn't actually disable it as If I adjust the Penumbra Scale setting (above it) it still causes the same issue but it shouldn't make a difference adjusting the Penumbra Scale as the description literally reads "Scales the radius of the blur caused by Variable Penumbra" but I had just turned off Variable Penumbra Shadows.

**Comment by Fichuwa** [comment] 2021-11-18 05:07
Setting Variable Penumbra Shadows scale from 1.0 to 3.0 seems to fix only issue on picture 4. Issues on picture 1-3 still persist. Thank you for the tip.

**Comment by rre36** [comment] 2023-06-07 16:48
should be fully fixed with 5.1a

**Closed as completed by rre36** 2023-06-07 16:48 UTC
Labels: Bug, Kappa Shader
