### ISSUE TITLE
Nostalgia: Sunlight is seen through blocks

### ISSUE THREAD

**Issue by amethyst-87** [rre36/ShaderpackIssueTracker#115] opened 2024-08-15 11:18 UTC
**Describe the bug**
Sun is weakly seen through blocks when in dark room/building.

**To Reproduce**
1. Enable shaderpack
2. Walk in a dark room and look in the direction of sun

**Expected behavior**
Dark wall.

**Screenshots**
![image](https://github.com/user-attachments/assets/5395c58b-e6ac-4ef1-a66a-1c8129e78754)

**Environment (please complete the following information):**
Iris Version: latest v1.7.3
Minecraft Version: 1.20
Shaderpack Version: 5.0
Graphics Card and Driver Version: 1050 Ti 4gb, latest driver
Operating System: Windows 10
CPU: i7-2600k (didn't overclock)
Amount of System Memory (total and assigned to Java): 16GB / 2GB assign.
Launcher: Legacy Launcher (i have a minecraft license)

**Comment by amethyst-87** [comment] 2024-08-15 16:17
![javaw_V0ZzErCrHc](https://github.com/user-attachments/assets/3cad78ac-f66a-4a2d-9f3e-94e0cd2d5f6e)
it's also seen through like every block

**Comment by rre36** [comment] 2024-09-12 10:17
Caused by an Iris bug, to be fixed in iris 1.8

**Closed as completed by rre36** 2024-09-12 10:17 UTC
Labels: Iris/Optifine Issue

**Comment by Cotton-PK** [comment] 2025-01-25 20:10
It's not:

![Image](https://github.com/user-attachments/assets/1ccf6bfe-932a-47a7-a3c2-ce613efcc02b)

![Image](https://github.com/user-attachments/assets/c585d70a-0097-4e06-8361-0eafe85cd8ac)
