### ISSUE TITLE
Some bugs underwater.

### ISSUE THREAD

**Issue by PickyPixelStudio** [rre36/ShaderpackIssueTracker#24] opened 2021-04-24 20:01 UTC
**Describe the bug**
When i try to go underwater, on my main PC i've no Caustic effect (GTX 1080) but on my second one, no problem (RTX 3070).
Shadows looks weird, and surligned with white effect.
And last, all of seaweed look illuminated, inside deep dark sea.

**To Reproduce**
1. Launch game
2. Go underwater
3. Tada... 

NB : I've the same settings on both PC, but not the same result... That weird.

**Expected behavior**
Explain what happens, and if possible, how to fix it.

**Screenshots**
Weird Shadows : 
https://imgur.com/eL3KVRS

Illuminated Seaweed :
https://imgur.com/OhMMwh8

No Caustic Effect :
https://imgur.com/ztoyqbE

**Environment (please complete the following information):**
Optifine Version: 1.16.5 HD U G7
Minecraft Version: 1.16.5
Shaderpack Version: Nostalgia 3.0
Graphics Card and Driver Version: GTX 1080 ()
Operating System: Windows 10
CPU: i7 10700k
Amount of System Memory (total and assigned to Java): Total : 16Go, Java : 8Go.

**Additional context**
Nop...

**Comment by xandercreates** [comment] 2021-04-25 18:00
Send a Screenshot with F3 open on your main PC

**Comment by xandercreates** [comment] 2021-04-25 18:04
Also, can you check if you get this issue with 1.16.5 HD U G8_pre12?

**Comment by PickyPixelStudio** [comment] 2021-04-25 19:58
> Send a Screenshot with F3 open on your main PC

Yep : 

https://imgur.com/qRjATIU




> Also, can you check if you get this issue with 1.16.5 HD U G8_pre12?

I got the same issue...

https://imgur.com/z4L16HB

I'll try with a previous version of the shader. Not sure if it's a good idea.

**Comment by PickyPixelStudio** [comment] 2021-04-25 20:00
Also i got some mods :

-AmbientSound
-BiomeOPlenty
-CreativeCore
-DynamicSurrounding

I tried with, and without other mod, nothing change.

**Comment by rre36** [comment] 2022-06-27 09:08
Underwater foliage and VPS artefacts have been fixed in a past update, lack of caustics is an unfixable issue caused by the nVidia driver on certain systems.

**Closed as completed by rre36** 2022-06-27 09:08 UTC
Labels: Bug, Nostalgia Shader
